import { GateDefinition } from '@/types/quantum';

export const GATE_DICTIONARY: Record<string, GateDefinition> = {
  H: {
    type: 'H',
    name: 'Hadamard Gate',
    symbol: 'H',
    description: 'Puts qubit into equal superposition of |0⟩ and |1⟩',
    matrix: '1/√2 * [ 1   1 ]\n        [ 1  -1 ]',
    color: 'from-cyan-500 to-blue-600 border-cyan-400',
    category: 'superposition',
  },
  X: {
    type: 'X',
    name: 'Pauli-X (NOT Gate)',
    symbol: 'X',
    description: 'Flips |0⟩ to |1⟩ and |1⟩ to |0⟩ (180° rotation around X-axis)',
    matrix: '[ 0  1 ]\n[ 1  0 ]',
    color: 'from-pink-500 to-rose-600 border-pink-400',
    category: 'pauli',
  },
  Y: {
    type: 'Y',
    name: 'Pauli-Y Gate',
    symbol: 'Y',
    description: 'Flips bit and phase (180° rotation around Y-axis)',
    matrix: '[ 0  -i ]\n[ i   0 ]',
    color: 'from-purple-500 to-indigo-600 border-purple-400',
    category: 'pauli',
  },
  Z: {
    type: 'Z',
    name: 'Pauli-Z (Phase Flip)',
    symbol: 'Z',
    description: 'Flips phase of |1⟩ state (180° rotation around Z-axis)',
    matrix: '[ 1   0 ]\n[ 0  -1 ]',
    color: 'from-emerald-500 to-teal-600 border-emerald-400',
    category: 'pauli',
  },
  S: {
    type: 'S',
    name: 'Phase Gate (S)',
    symbol: 'S',
    description: 'Rotates phase by 90° (π/2) around Z-axis',
    matrix: '[ 1   0 ]\n[ 0   i ]',
    color: 'from-amber-500 to-orange-600 border-amber-400',
    category: 'phase',
  },
  T: {
    type: 'T',
    name: 'π/8 Gate (T)',
    symbol: 'T',
    description: 'Rotates phase by 45° (π/4) around Z-axis',
    matrix: '[ 1      0     ]\n[ 0  e^(iπ/4) ]',
    color: 'from-violet-500 to-fuchsia-600 border-violet-400',
    category: 'phase',
  },
  M: {
    type: 'M',
    name: 'Measurement Operator',
    symbol: 'M',
    description: 'Collapses quantum superposition into classical bit 0 or 1',
    matrix: 'P(0) = |α|², P(1) = |β|²',
    color: 'from-blue-600 to-indigo-800 border-blue-400',
    category: 'measurement',
  },
};
